namespace TownOfUs
{
    public enum CustomRPC
    {
        SetRole = 100,
        SetModifier,
        SetCouple,
        SetAssassin,
        SetTarget,
        SetGATarget,
        SetHeretic,
        SetUndercover,
        MonarchKnight,

        SetPhantom,
        CatchPhantom,

        SetHaunter,
        CatchHaunter,

        SetPoltergeist,
        CatchPoltergeist,

        SetTraitor,
        TraitorSpawn,

        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        NobodyWins,
        ApocalypseWin0,
        ApocalypseWin1,
        ApocalypseWin2,
        ApocalypseWin3,
        ApocalypseWin4,
        ApocalypseWin5,
        ApocalypseWin6,
        ApocalypseWin7,
        WerewolfWin,
        SurvivorOnlyWin,
        VampireWin,
        SerialKillerWin,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetSwaps,
        Protect,
        AttemptSound,
        Morph,
        Mine,
        Swoop,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        DoomsayerKill,
        PirateKill,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        Vest,
        GAProtect,
        Blackmail,
        Infect,
        TurnPestilence,
        TurnFamine,
        TurnWar,
        TurnDeath,
        Disperse,
        Escape,
        Revive,
        Convert,
        ChameleonSwoop,
        Imitate,
        StartImitate,
        Bite,
        Reveal,
        Prosecute,
        Confess,
        Bless,
        Camouflage,
        SnitchCultistReveal,
        Duel,
        ChangeDefence,

        BypassKill,
        BypassMultiKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        RemoveAllBodies,
        CheckMurder,

        SubmergedFixOxygen,

        RedWin,
        BlueWin,
        YellowWin,
        GreenWin,

        SoloKillerWin,

        Roleblock,
        Poison,
        Shoot,
        BugPlayer,
        UnroleblockPlayer,
        UnbugPlayers,
        BugMessage,
        ControlSet,
        ControlPerform,
        ControlCooldown,
        SoulSwap
    }
}
