namespace TownOfUs
{
    public enum CustomRPC
    {
        SetRole = 100,
        SetModifier,
        SetObjective,
        SetCouple,
        SetAssassin,
        SetTarget,
        SetGATarget,
        SetHeretic,
        SetUndercover,
        MonarchKnight,

        SetPhantom,
        CatchPhantom,

        SetHaunter,
        CatchHaunter,

        SetPoltergeist,
        CatchPoltergeist,

        SetTraitor,
        TraitorSpawn,

        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        NobodyWins,
        ApocalypseWin,
        WerewolfWin,
        SurvivorOnlyWin,
        VampireWin,
        SerialKillerWin,
        NecromancerWin,
        JackalWin,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetSwaps,
        Protect,
        AttemptSound,
        Morph,
        Mine,
        Swoop,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        DoomsayerKill,
        PirateKill,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        Vest,
        GAProtect,
        Blackmail,
        Infect,
        TurnPestilence,
        TurnFamine,
        TurnWar,
        TurnDeath,
        Disperse,
        Escape,
        Revive,
        Convert,
        ChameleonSwoop,
        Imitate,
        StartImitate,
        Bite,
        Reveal,
        Prosecute,
        Confess,
        Bless,
        Camouflage,
        SnitchCultistReveal,
        HunterStalk,
        HunterCatchPlayer,
        Retribution,
        Duel,
        ChangeDefence,

        BypassKill,
        BypassMultiKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        RemoveAllBodies,
        CheckMurder,

        SubmergedFixOxygen,

        ContentAddition,

        RedWin,
        BlueWin,
        YellowWin,
        GreenWin,

        SoloKillerWin,

        Roleblock,
        Poison,
        Shoot,
        BugPlayer,
        UnroleblockPlayer,
        UnbugPlayers,
        BugMessage,
        ControlSet,
        ControlPerform,
        SoulSwap,
        AbilityUsed,
        KillAbilityUsed,
        JKRevive,
        SetRecruit,
        DeputyShoot,
        Fortify,
        Unfortify,
        Guard,
        Unguard,
        Barrier,
        Unbarrier,
        SetChat,
        VisionPlayer,
        VisionInteract,
        DemagogueKill,
        DemagogueVotes,
        DemagogueConvince,
        DemagogueCharges,
        GodfatherRecruit,
        IsMeeting,
        PoisonKill,

        RpcExpand = 255
    }
}
